import placeholder from "../../images/Trustprofile02.png";


export const embroideryServices = [
  {
    id: 1,
    title: "Custom Embroidery Digitizing",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

  {
    id: 2,
    title: "Cap Digitizing",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
     active: true,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

  {
    id: 3,
    title: "Jacket Back Digitizing",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

  {
    id: 4,
    title: "Left Chest Digitizing",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

  {
    id: 5,
    title: "Applique Embroidery Digitizing",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 6,
    title: "Custom Embroidery Digitizing",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 7,
    title: "Custom Embroidery Digitizing",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 8,
    title: "Custom Embroidery Digitizing",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 9,
    title: "Custom Embroidery Digitizing",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 10,
    title: "Custom Embroidery Digitizing",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

];
export const vectorTracingServices = [
  {
    id: 1,
    title: "VECTOR TRACING",
    image: placeholder,
    price: "$15",
    logoType: "ART",
    active: true,
    features: [
      "FAST DELIVERY",
      "PRINT READY FILE",
      "UNLIMITED REVISIONS",
      "AI, EPS, SVG, PDF",
        ],
  },

  {
    id: 2,
     title: "DTF Design Preparation",
    image: placeholder,
    price: "$15",
    logoType: "ART",
    active: false,
    features: [
      "FAST DELIVERY",
      "PRINT READY FILE",
      "UNLIMITED REVISIONS",
      "AI, EPS, SVG, PDF",
    ],
  },

  {
    id: 3,
    title: "Engraving Design",
    image: placeholder,
    price: "$15",
    logoType: "Art",
     active: false,
    features: [
      "FAST DELIVERY",
      "PRINT READY FILE",
      "UNLIMITED REVISIONS",
      "AI, EPS, SVG, PDF",
    ],
  },

  {
    id: 4,
    title: "Screen Printing Design",
    image: placeholder,
    price: "$15",
    logoType: "Art",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

  {
    id: 5,
    title: "Laser Cutting Design",
    image: placeholder,
    price: "$15",
    logoType: "Art",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 6,
    title: "Sublimation Design",
    image: placeholder,
    price: "$15",
    logoType: "Art",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
 {
    id: 7,
    title: "Digital Printing Design",
    image: placeholder,
    price: "$15",
    logoType: "Art",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 8,
    title: "Die Cutting Design",
    image: placeholder,
    price: "$15",
    logoType: "Art",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 9,
    title: "Offset Printing Design",
    image: placeholder,
    price: "$15",
    logoType: "Art",
    //  active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 10,
    title: "Flexographic Printing Design",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
    //  active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 11,
    title: "High resolution png",
    image: placeholder,
    price: "$15",
    logoType: "LOGO",
    //  active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

];
export const logoDesignServices = [
  {
    id: 1,
    title: "Minimal Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

  {
    id: 2,
    title: "Modern Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

  {
    id: 3,
    title: "Wordmark Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

  {
    id: 4,
    title: "Combination Mark Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

  {
    id: 5,
    title: "Mascot Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 6,
    title: "Lettermark Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 7,
    title: "Monogram Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 8,
    title: "Abstract Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 9,
    title: "Emblem Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
  {
    id: 10,
    title: "Icon Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
   {
    id: 11,
    title: "Typography Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },
     {
    id: 12,
    title: "Flat Logo",
    image: placeholder,
    price: "$100",
    logoType: "LOGO",
     active: false,
    features: [
      "Fast Delivery",
      "100% Quality Work",
      "All File Formats",
      "Unlimited Revisions",
    ],
  },

];